#!/usr/bin/env perl
package main;
use v5.10;
use autodie;
use strict;
use utf8;
binmode STDOUT, ':utf8';
use Data::Dumper 'Dumper';
use POSIX; 'WNOHANG';
use Time::HiRes 'sleep';

# Don't buffer STDOUT
$| = 1;

my %builtin = (
  cd   => sub { chdir $_[0] || warn "Couldn't chdir to $_[0]: $!\n" },
  exit => sub { exit $_[0] || 0 },
);

while (1) {
  print "🐫 ";
  my $command = <>;
  chomp $command;
  next unless $command;
  run($command);
}

sub run {
  my $raw_text = shift;
  my @commands = reverse @{parse($raw_text)};
  for (0..$#commands) {
    my %command = %{$commands[$_]};
    if ($builtin{$command{program}}) {
      $builtin{$command{program}}->(@{$command{args}});
      return;
    }
    my $pid = fork;
    if (! defined $pid) { print STDERR "Couldn't fork: $!\n" }
    elsif ($pid == 0) {
      # Handle pipes
      if ($command{writer}) {
        open STDOUT, '>&', $command{writer};
        $| = 1;
      }
      elsif ($command{reader}) {
        open STDIN, '<&', $command{reader};
      }
      # Handle redirections
      if ($command{stdin}) {
        open STDIN, "<", $command{stdin};
      }
      if ($command{stdout}) {
        open STDOUT, $command{append}, $command{stdout};
      }
      # we exit here if this succeeds
      exec $command{program}, @{$command{args}};
    }
  }
  do {
    sleep(0.25);
  } while (waitpid(-1, WNOHANG) > 0) # until all children exit
}
sub parse {
  my @words = grep $_ =~ /\S/, split /( \s+ | < | >> | > )/x, shift;
  my @commands = ();
  while (@words) {
    local $_ = shift @words;
    # first word is a command
    if (@commands == 0) {
      push @commands, {program => $_, args => []};
    }
    elsif ($_ eq '|') {
      pipe my $read, my $write;
      $commands[-1]{writer} = $write;
      push @commands, {program => shift(@words), args => [], reader => $read};
    }
    elsif ($_ eq '<') {
      $commands[-1]{stdin} = shift @words;
    }
    elsif ($_ eq '>' || $_ eq '>>') {
      $commands[-1]{stdout} = shift @words;
      $commands[-1]{append} = $_;
    }
    else {
      push @{$commands[-1]{args}}, $_;
    }
  }
  return \@commands;
}
